FROM mcr.microsoft.com/dotnet/sdk:6.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["src/Be3Test.Api/Be3Test.Api.csproj", "src/Be3Test.Api/"]
COPY ["src/Be3Test.Domain/Be3Test.Domain.csproj", "src/Be3Test.Domain/"]
COPY ["src/Be3Test.Infra/Be3Test.Infra.csproj", "src/Be3Test.Infra/"]

RUN dotnet restore "src/Be3Test.Api/Be3Test.Api.csproj"
COPY . .
WORKDIR "/src/src/Be3Test.Api"
RUN dotnet build --no-restore "Be3Test.Api.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]